### ISSUE TITLE
Edge Extension?

### ISSUE THREAD

**Issue by dlNone** [OllieTerrance/Homely#31]
Is it possible to make a edge version? I like your extension very much. I recently wanted to migrate from Chrome to Edge. I try to install this extension in edge, but it seems there is a bug and the homepage cannot be displayed normally.
__
Error handling response: TypeError: Cannot read properties of undefined (reading 'content')
    at chrome-extension://fplghnonomhbnlhdnmjpipoomkjdpeim/res/js/homely.js:288:61

**Comment by Terrance** [comment]
As Edge is just Chrome under the hood, you should be able to install and use it from the Chrome Web Store without issue:

![image](https://github.com/Terrance/Homely/assets/4025899/066d107c-e088-40ce-b135-5c52ed010888)

Note that Edge apparently considers extensions that modify the new tab page as malicious and disables them after installation.

> Error handling response: TypeError: Cannot read properties of undefined (reading 'content')
> at chrome-extension://fplghnonomhbnlhdnmjpipoomkjdpeim/res/js/homely.js:288:61

This looks like your settings aren't being loaded correctly -- have you used the extension in Edge before and have residual settings lying around, or restored a backup from another browser?

You can try opening Developer Tools (F12) and resetting your settings by typing into the Console tab:

```js
chrome.storage.local.clear()
```
